### ISSUE TITLE
Task 1 Challenge mode breaking while generating the submission files 

### ISSUE THREAD

**Issue by rohit21122012** [TUT-ARG/DCASE2016-baseline-system-python#4]
The `on_after_extract()` function in "src/dataset.py" at line no 1126 appears to expect a "evaluate.txt" file in the "evaluation_setup" folder which is not the case (it is named 'test.txt') in the dataset :
`eval_filename = os.path.join(self.evaluation_setup_path, 'evaluate.txt')`

Also, while generating the meta file out of the "evaluate.txt", since there are no labels, it results in an index error while accessing row[1] at line no 1136 of "src/dataset.py" :
`meta_data[row[0]] = row[1]`

Another suggestion - while initializing the challenge dataset in line no 178 of "task1_scene_classification.py", the data path is not considered. The data path could have been added similar to the development dataset initialization :
`challenge_dataset = eval(params['general']['challenge_dataset'])()`

**Comment by toni-heittola** [comment]
The issue raised for `on_after_extract()` is not valid. The code does not expect "evaluate.txt", it will generate "meta.txt" file only in the case when "evaluate.txt" file exists. Currently "evaluate.txt" file is not yet published, however, it will be in some time after DCASE2016 challenge, and therefore the code is there already.

The second issue is valid, and this has been fixed in the fcdca51e3c91b4da2049e4bdaaea8c068ac6aa80
